> match_1_0223_c3, PILLKSIITAILMALIVLLIFLLWWLLMLLR
--KKKSXXTAXXMAXXVLXXFLXWWXXKK

KKKSLVTAALMALLVLLLFLFWWLLKK


> match_1_0813_c2, PALLLSLIMGILMALLILIIFLLLLLLRLR
--KKKSXXMGXXMAXXILXXFXXXWKKK--

KKKSLVMGLLMALAILLLFFLLWKKK

> EGFR itself
