> match_1_0223_c3, PILLKSIITAILMALIVLLIFLLWWLLMLLR
--KKKSXXTAXXMAXXVLXXFLXWWXXKK

KKKSLVTAALMALLVLLLFLFWWLLKK


> match_1_0813_c2, PALLLSLIMGILMALLILIIFLLLLLLRLR
--KKKSXXMGXXMAXXILXXFXXXWKKK--

KKKSLVMGLLMALAILLLFFLLWKKK

> EGFR itself, ggc +4

CGGGKKSIATGMVGALLLLLVVALGIGLFMKK

> match_1_0223_c3, ggc +8

CGGGKKKKSLVTAALMALLVLLLFLFWWLLKKKK

> match_1_0813_c2, ggc + 8

CGGGKKKKLSLVMGLLMALAILLLFFLLWKKKK